development:
  clients:
    default:
      database: mongoid_dev
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
    log_level: debug
test:
  clients:
    default:
      database: mongoid_test
      hosts:
        - mongo:27017
