development:
  clients:
    default:
      database: mongoid_dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017
