apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-back-deployment
  labels:
    app: app-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-back
  template:
    metadata:
      labels:
        app: app-back
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "db:27017"
    spec:
      containers:
        - name: app-back
          image: graphql-sinatra-puma
          ports:
            - containerPort: 4000
          env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_TOKEN
              value: "s.1XMLF3RE0yRJL9vxBvUo3vsT"

---
apiVersion: v1
kind: Service
metadata:
  name: app-back
spec:
  selector:
    app: app-back
  ports:
    - protocol: TCP
      port: 4000
