version: 2.1

jobs:
  plan-apply:
    working_directory: ~/automated-deploy/infra/prod
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout:
          path: ~/automated-deploy
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .
  node-tests:
    working_directory: ~/automated-deploy/frontend
    docker:
      - image: node:current-alpine
    steps:
      - checkout:
          path: ~/automated-deploy
      - run:
          name: install dependencies and run tests
          command: |
            yarn install
            yarn jest
  ruby-tests:
    working_directory: ~/automated-deploy/backend
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout:
          path: ~/automated-deploy
      - run:
          name: install docker-compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.28.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: run tests
          command: |
            ./run_ci_tests.sh

workflows:
  # prod:
  #   jobs:
  #     - plan-apply
  #     - hold-apply:
  #         type: approval
  #         requires:
  #           - plan-apply
  #     - apply:
  #         requires:
  #           - hold-apply
  #     - plan-destroy:
  #         requires:
  #           - apply
  #     - hold-destroy:
  #         type: approval
  #         requires:
  #           - plan-destroy
  #     - destroy:
  #         requires:
  #           - hold-destroy
  dev:
    jobs:
      - node-tests
      - ruby-tests
